### ISSUE TITLE
Why use this over lodash/underscore _.pick?

### ISSUE THREAD

**Issue by markogresak** [sindresorhus/filter-obj#1]
I believe [`lodash.pick`](https://www.npmjs.com/package/lodash.pick) includes the same functionality as this module describes. I don't want to sound like hater, but I think there are enough utility libraries and reinventing the wheel isn't such a good idea.

**Comment by sindresorhus** [comment]
Why use `lodash.pick` over `underscore.pick`?
Why use `underscore.pick` over `mootools.Object.filter`?
Why ...

This is tiny, fast and simple. `lodash.pick` is dense, fast and feature rich. Different needs for different situations. I usually use Lodash for apps/servers, but try to stay away from it in tiny reusable modules as it usually comes with a large dependency tree.
