### ISSUE TITLE
This changes whether a property is writable or configurable

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/filter-obj#20]
The new properties returned by this library are always writable and configurable, even when the original properties were not. While non-writable or non-configurable properties are sometimes problematic, there are sometimes legitimate reasons for it. This seems to be an unintentional side effect.

```js
const obj = Object.defineProperty({}, 'prop', { value: true, enumerable: true, writable: false, configurable: false })
const objCopy = includeKeys(obj, ['prop'])
console.log(Object.getOwnPropertyDescriptor(objCopy, 'prop'))
// { value: true, writable: true, enumerable: true, configurable: true }
```

Additionally, when a property is using `get`/`set`, they are currently removed.

```js
const obj = Object.defineProperty({}, 'prop', { get: () => Math.random(), enumerable: true })
console.log(obj.prop, obj.prop) // Different random numbers
const objCopy = includeKeys(obj, ['prop'])
console.log(objCopy.prop, objCopy.prop) // Same random numbers
```

Instead of retrieving then copying the property values, the descriptors should be used instead.

https://github.com/sindresorhus/filter-obj/blob/36e5f3a87cadeed6ef1d2da8f0362d048d3720e5/index.js#L8
https://github.com/sindresorhus/filter-obj/blob/36e5f3a87cadeed6ef1d2da8f0362d048d3720e5/index.js#L20

Note: I can submit a PR.

**Comment by sindresorhus** [comment]
Thanks for catching that. PR welcome.

**Comment by ehmicky** [comment]
Done in #22.
