### ISSUE TITLE
Optional chaining  is poor compatibility. may cause the error:   uncaught syntaxerror unexpected token ' .'

### ISSUE THREAD

**Issue by webhaoying** [sindresorhus/filter-obj#31]
[Optional chaining](https://github.com/sindresorhus/filter-obj/blob/main/index.js)  has poor compatibility.
advice some  compatiable method .
<img width="999" alt="image" src="https://user-images.githubusercontent.com/26812135/217771042-c3c30c69-e209-44e6-b6f7-9f313a8552c0.png">

<img width="817" alt="image" src="https://user-images.githubusercontent.com/26812135/217770527-3a35fe19-394d-4803-ae3e-f4dfb42c1bb5.png">

**Comment by sindresorhus** [comment]
This package targets modern platforms. If you need to support legacy platforms, it's up to you to transpile the code with Babel.
