### ISSUE TITLE
Support `Set`s

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/filter-obj#35]
Since the array case treats it like an iterable, we could replace the check with `Array.isArray` for a check with `[Symbol.iterator]`.

We shouldn't just use `instanceof Set` because: https://github.com/sindresorhus/is#why-not-just-use-instanceof-instead-of-this-package

**Comment by sindresorhus** [comment]
👍

**Comment by ehmicky** [comment]
Should any iterable be allowed?

For example, passing a string is most likely a mistake. But they are iterables.

**Comment by sindresorhus** [comment]
Hm, yeah. Thinking more about this; Supporting an iterable makes sense when you can actually take advantage of it being an iterable (maybe lazy), but in this case, we just iterate over it, so there is no benefit of it being an iterable.
