### ISSUE TITLE
How Filter child objects present within root json object??

### ISSUE THREAD

**Issue by DheerajKN** [sindresorhus/filter-obj#6]
For Instance, let consider we have a JSON.

```js
const person = {
  name: "John Doe",
  age: 27,
  kids:[
    {
      name: "James Doe",
      age: 7
    },
    {
      name: "Mary Doe",
      age: 7
    }
  ]
}
```

how to write the filter-obj so that I can get this solution.

filterObject(person, ['name', 'kids??']) 
I tested it locally neither `kids.name, kids[name], kids{name}` worked!!

```js
const person = {
  name: "John Doe",
  kids:[
    {
      name: "James Doe"
    },
    {
      name: "Mary Doe"
    }
  ]
}
```

**Comment by sindresorhus** [comment]
`includeKeys` doesn't support nested keys. It's meant for top-level keys. You can use `filter` instead. Or use Lodash, which has support for nested keys.

**Comment by faizanu94** [comment]
@DheerajKN even if there's support for nested keys, for how much levels will it be required? @sindresorhus would it be optimal to use a parameter to enable/disable nested filtering?

**Comment by sindresorhus** [comment]
The `filter` parameter can solve this. I don't want to add support for nesting with the keys parameter.
